gribi_message {
  node_address: "dns:///[2607:f8b0:f803:160b::1]:9340"
  get_response {
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.70.0.24/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.70.0.27/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.70.0.28/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653270
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653285
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653285
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.11/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653285
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.14/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.15/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.17/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.18/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.19/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.20/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.22/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.24/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.71.0.25/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653285
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653270
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653285
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.11/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653285
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.14/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.17/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.18/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.19/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.20/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.72.0.22/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653285
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653282
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653282
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.14/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653285
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.15/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.18/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.19/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.20/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.21/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.22/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.75.0.24/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653282
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653264
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653273
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653279
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653264
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653273
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653273
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.14/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653264
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.15/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.17/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.18/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.19/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653279
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.20/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.21/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.22/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.23/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653273
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.79.0.24/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653273
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.84.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.84.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.84.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653282
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.84.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653261
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.84.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.84.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.84.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653276
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.84.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.84.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.84.0.11/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.84.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653288
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "98.84.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\002\000\031\000\000"
          }
          next_hop_group {
            value: 402653267
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
  }
}
