gribi_message {
  node_address: "dns:///[2607:f8b0:f803:160b::1]:9340"
  get_response {
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.11/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.15/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.17/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.18/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.20/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.21/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.22/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653397
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.23/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.24/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.26/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.29/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.30/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.61.0.31/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653397
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653397
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653397
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.14/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.17/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.18/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.19/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.21/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.22/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.23/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.24/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653385
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.62.0.25/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653382
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653391
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653382
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.11/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.14/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.15/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.17/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.18/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653382
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.19/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.20/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.21/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.23/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653382
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.24/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.27/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.28/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.29/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.68.0.30/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653382
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653391
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653382
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.11/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.14/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.15/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.19/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653382
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.20/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.21/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.22/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.23/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653382
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.24/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.25/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.26/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.27/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.29/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.69.0.34/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.70.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.70.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.70.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653370
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.70.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.70.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.70.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653391
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.70.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.70.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653370
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.70.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
  }
}
