gribi_message {
  node_address: "dns:///[2607:f8b0:f803:160b::1]:9340"
  get_response {
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.1.0.43/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.1.0.44/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.1.0.48/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.1.0.49/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653208
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653220
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653220
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653211
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653220
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653220
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653208
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.11/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653211
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.14/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.17/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.19/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653220
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.23/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.24/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.25/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.2.0.26/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653217
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653232
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653232
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.15/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.17/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.18/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.19/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.21/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.24/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.25/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653220
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.27/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.28/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653232
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.29/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653217
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.33/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.35/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.36/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.38/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.39/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.41/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.43/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.50/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.3.0.51/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653217
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653220
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653217
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653214
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653220
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653211
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.15/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653220
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.17/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.18/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.19/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.20/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653217
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.21/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.22/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653217
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.23/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653220
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.25/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653214
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.30/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653226
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.31/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653214
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.32/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653214
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.4.0.33/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653232
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653217
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653220
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.17/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.18/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.20/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653235
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.22/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.23/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653217
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.24/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "REPAIRED"
      ipv4 {
        prefix: "101.5.0.25/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\001\000\031\000\000"
          }
          next_hop_group {
            value: 402653229
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
  }
}
