gribi_message {
  node_address: "dns:///[2607:f8b0:f803:160b::1]:9340"
  get_response {
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653382
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.11/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.15/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653382
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.18/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.21/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.22/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.26/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653376
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.207.0.27/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653382
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653370
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653385
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653385
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653370
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.14/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.15/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.17/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.18/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653385
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.19/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.24/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.212.0.25/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653397
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653385
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653385
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.11/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.19/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.23/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653385
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.25/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653385
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.213.0.26/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653370
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653391
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653391
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.11/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.14/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.15/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.17/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.20/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.21/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.22/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.23/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.25/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.214.0.27/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653397
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.5/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.6/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.7/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.8/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.9/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.10/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653385
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.11/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.12/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.13/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.16/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.18/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653397
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.19/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.20/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653385
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.21/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653388
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.22/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.23/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.25/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.26/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.27/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.30/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653379
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.223.0.31/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653397
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.224.0.0/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653373
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.224.0.1/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.224.0.2/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653397
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.224.0.3/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653385
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
    entry {
      network_instance: "VRF-blue"
      ipv4 {
        prefix: "112.224.0.4/32"
        ipv4_entry {
          entry_metadata {
            value: "\200\000\000\004\000\031\000\000"
          }
          next_hop_group {
            value: 402653394
          }
        }
      }
      rib_status: PROGRAMMED
      fib_status: PROGRAMMED
    }
  }
}
